/*
 *
 * MapView constants
 *
 */

export const INITIALIZE_MARKERS = 'app/MapView/INITIALIZE_MARKERS';
export const INITIALIZE_MARKERS_ERROR = 'app/MapView/INITIALIZE_MARKERS_ERROR';
export const INITIALIZE_MARKERS_SUCCESS = 'app/MapView/INITIALIZE_MARKERS_SUCCESS';
export const UPDATE_LOCATION = 'app/MapView/UPDATE_LOCATION';
export const SET_OUT_OF_OFFICE = 'app/MapView/SET_OUT_OF_OFFICE';
export const SET_OUT_OF_OFFICE_SUCCESS = 'app/MapView/SET_OUT_OF_OFFICE_SUCCESS';
export const UPDATE_LOCATION_SUCCESS = 'app/MapView/UPDATE_LOCATION_SUCCESS';
export const BATCH_UPDATE_LOCATION = 'app/MapView/BATCH_UPDATE_LOCATION';
export const BATCH_UPDATE_LOCATION_SUCCESS = 'app/MapView/BATCH_UPDATE_LOCATION_SUCCESS';
export const DEREGISTER_VEHICLE = 'app/MapView/DEREGISTER_VEHICLE';
